#!url=https://raw.githubusercontent.com/tszchun0915/Shadowrocket/refs/heads/main/YTMod.Module
#!name=YT(Music)Enhance M
#!desc=PiP+Ambient Mode enabled - Optimized
#!arguments=請求處理服務:https://stream.maasea.workers.dev, 屏蔽上傳按鈕:true, 屏蔽選段按鈕:true, 屏蔽Shorts按鈕:false, 字幕翻譯語言:zh-Hant, 歌詞翻譯語言:zh-Hant, 啟用調試模式:false, 腳本執行引擎:webview
#!arguments-desc=- 屏蔽參數：[true, false]\n- 翻譯參數：[語言代碼, off]\n- 腳本執行引擎:[jsc, webview]
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

[Rule]
AND,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT
AND,((URL-REGEX,(^https?:\/\/([\w-]+)\.googlevideo\.com\/initplayback(\?.*oad=.+)$)),(PROTOCOL,UDP)),REJECT-200

[URL Rewrite]
# 正常影片流量優先處理
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
(https?:\/\/[\w-]+\.googlevideo\.com\/.+?)(&ctier=L|\/ctier\/L)((&|\/).+?)(,ctier|%2Cctier)((,|%2C).+) $1$3$6 302

# 攔截廣告影片流
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback(\?.*oad=.*)? _ reject-200
^https?:\/\/[\w-]+\.googlevideo\.com\/.*&pltype=ad.* _ reject-200
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200

# 攔截統計追蹤
^https?:\/\/s\.youtube\.com\/api\/stats\/(ads|qoe\?adcontext|adsense.*|gfp_.*) _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking|get_midroll|.*ad_break.*|.*ad_.+?\.js) _ reject-200

# 攔截 DoubleClick
^https?:\/\/[^\/]*\.doubleclick\.net\/ _ reject-200

# API 轉發（去廣告核心）
^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$ {{{請求處理服務}}}/$1?blockUpload={{{屏蔽上傳按鈕}}}&blockImmersive={{{屏蔽選段按鈕}}}&blockShorts={{{屏蔽Shorts按鈕}}}&engine={{{腳本執行引擎}}}&captionLang={{{字幕翻譯語言}}}&lyricLang={{{歌詞翻譯語言}}}&$4 307

[MITM]
hostname = %APPEND% www.youtube.com, s.youtube.com, music.youtube.com, youtubei.googleapis.com, *.googlevideo.com, -gemini.google.com, -generativelanguage.googleapis.com
